### ISSUE TITLE
start-jutsu! fails because of missing browser

### ISSUE THREAD

**Issue by alanmarazzi** [hswick/jutsu#11]
```clojure
(j/start-jutsu! 4000 false)
Starting http-kit...

java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
```

I'm trying to launch Jutsu from an environment without a browser and it fails even with `display = false`

**Comment by hswick** [comment]
Oops!

Looks like the issue is here https://github.com/hswi ck/jutsu/blob/master/src/clj/jutsu/web.clj#L120

The when doesn't check display :p

Pushing out a new release now.

**Comment by hswick** [comment]
`0.1.3` is on clojars!
