### ISSUE TITLE
Trouble with plotting over 100 items

### ISSUE THREAD

**Issue by viesti** [hswick/jutsu#8]
Hi! I tried out this neat library, but had trouble plotting more than 100 items. 

The below:

```clojure
(j/graph! "Testing"
                [{:y (range 1000)
                  :x (range 1000)
                  :mode "markers"
                  :type "scatter"
                  :name "testing"}])
```

gives only 100 items in the plot (see ellipsis at end of `:x` and `:y`):

![image](https://user-images.githubusercontent.com/57011/35114149-75894954-fc8c-11e7-9de9-a7e846231c27.png)

**Comment by hswick** [comment]
Hi, that seems rather strange. One issue might be that I believe range is a lazy sequence.

**Comment by viesti** [comment]
Yes, odd thing that using a vector yields same result,

```clojure
(j/graph! "Testing3"
                [{:y (mapv inc (range 1000))
                  :x (mapv dec (range 1000))
                  :mode "markers"
                  :type "scatter"
                  :name "testing"}])
```

gives

![image](https://user-images.githubusercontent.com/57011/35115518-2e503598-fc91-11e7-9cc1-33d41109aa5c.png)

Note the brackets ([]) but still precense of ellipsis.

**Comment by viesti** [comment]
Maybe updating to newest Sente could solve this (didn't try yet though)?

**Comment by viesti** [comment]
Turns out that I had `*print-length*` set to 100 in my `~/.lein/profiles.clj` :facepalm:

**Comment by hswick** [comment]
Ha! I'll make sure to keep that in mind next time someone has a similar issue
